/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDHgXk2XeUwR5oUh7zFQ",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        vpcConfig: {
            vpcId: "vpc-0034494c10a7de603",
            securityGroupIds: [
                "sg-07a074477028e30ab"
            ],
            subnetAvailabilityZones: [
                {
                    subnetId: "subnet-01287b496197a0555",
                    availabilityZone: "us-east-2c"
                },
                {
                    subnetId: "subnet-01cc1eadd834dda7d",
                    availabilityZone: "us-east-2b"
                },
                {
                    subnetId: "subnet-02330974735132e31",
                    availabilityZone: "us-east-2a"
                }
            ]
        }
    }
}).schema({
    "food_items": a.model({
        id: a.integer().required(),
        name: a.string().required(),
        calories: a.integer().required()
    }).identifier([
        "id"
    ])
});
